version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: personal-website-prod
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.personal-website.rule=Host(`patste.me`)"
      - "traefik.http.routers.personal-website.entrypoints=websecure"
      - "traefik.http.routers.personal-website.tls.certresolver=letsencrypt"
    networks:
      - web

networks:
  web:
    external: true 